### ISSUE TITLE
Autonomous Routines

### ISSUE THREAD

**Issue by michael-brennan2005** [fairviewrobotics/2023-robot-code#13]
Routine 1a: 
* Starts on left side
* Places preloaded item

Routine 1b:
* Builds off routine 1a
* Goes to the center and picks up far left item
* Goes back to place it on peg/tray.

Routine 1c: 
* Builds off routine 1c
* Goes back to the center and picks up item from center
* Places item on peg/tray
* Goes back towards the center line to be ready to go for the community (1m behind center line)

Development order should be 1a -> 1b -> 1c. In the end you will really only have one routine here, the final routine 1c. Going through all three though will make testing/tuning easier and ensure we have something if we can't get routine 1c to work.

Routine 2a, 2b, 2c:
Same as routine 1, just that instead of starting on the left side, this will be  on the right side. Development order should be 1a -> 1b -> 1c.

Routine 3:
* Starts in the center
* Places preloaded item
* Goes onto balance beam, in the middle for now.

**Comment by zanealoia** [comment]
Routines 1a, 1b, 1c, 2a, 2b, 2c, and 3 have been developed with a space to input commands for the movement of the arm and elevator.
