### ISSUE TITLE
Before finishing touches

### ISSUE THREAD

**Issue by michael-brennan2005** [fairviewrobotics/2023-robot-code#43]
This is a pretty broad to do list of everything that needs to be done before we can go into full finishing touches/finalization mode:

* Finish the electrical rework of the arm and intake. (DONE)
* Cone routines: Picking downed cones and upright cones, placing on rings. (DONE: Chute pickup, high cone, IN PROGRESS: Mid place)
* Routine for placing on the floor. (DONE)
* Vision routines: align to apriltag/peg and lock side to side movement.
* Controls: We need to finalize with Duncan/Ashley what they like and implement it. Pitch to them the idea of ashley setting "mode" (cone or cube, high rung or mid rung) and Duncan clicking button to actually do action, I think this would work really well. (DONE)
* Autonomous balancing routine. (DONE)

Mechanical is effectively done with the robot minus minor tweaks. We should aim to have these finished by next Monday, and spend Tuesday + Wednesday doing final touches, inspections, and packing the robot.

**Comment by zanealoia** [comment]
Controls finished. Just need to run them by the drivers.

**Comment by zanealoia** [comment]
Electrical can be marked as finished. Controls and balancing routines have been made but not tested.

**Comment by zanealoia** [comment]
Controls and autonomous balancing routine can be marked as done. Cone routines also has high cone done, just need to test mid cone and floor placement.
